import { beforeEach, describe, expect, it, vi } from 'vitest';
import {
	GitHubAdapter,
	GitHubTransportContractError,
} from '../src/adapters/github';

const obsidianPlatform = vi.hoisted(() => ({
	isMobile: false,
	isMobileApp: false,
}));
const requestUrl = vi.hoisted(() => vi.fn());

vi.mock('obsidian', () => ({ Platform: obsidianPlatform, requestUrl }));

const PLUGIN_VERSION = '0.2.0-test';
const VALID_HEADERS = {
	Accept: 'application/vnd.github+json',
	'User-Agent': `DevRadar/${PLUGIN_VERSION} (https://github.com/FerdiHS/devradar)`,
	'X-GitHub-Api-Version': '2026-03-10',
};

describe('Obsidian GitHub transport boundary', () => {
	beforeEach(() => {
		requestUrl.mockReset();
		obsidianPlatform.isMobile = false;
		obsidianPlatform.isMobileApp = false;
	});

	it('uses requestUrl for an approved GitHub endpoint', async () => {
		requestUrl.mockResolvedValue({
			status: 200,
			headers: {},
			text: '{"ok":true}',
		});
		const { createObsidianGitHubTransport } =
			await import('../src/adapters/github-transport');
		const transport = createObsidianGitHubTransport(PLUGIN_VERSION);

		await expect(
			transport({
				url: 'https://api.github.com/users/octocat',
				headers: VALID_HEADERS,
			}),
		).resolves.toEqual({
			status: 200,
			headers: {},
			json: { ok: true },
		});
		expect(requestUrl).toHaveBeenCalledOnce();
	});

	it('accepts requests generated by GitHubAdapter', async () => {
		requestUrl.mockResolvedValue({
			status: 200,
			headers: {},
			text: JSON.stringify({ login: 'octocat', id: 42, type: 'User' }),
		});
		const { createObsidianGitHubTransport } =
			await import('../src/adapters/github-transport');
		const github = new GitHubAdapter({
			pluginVersion: PLUGIN_VERSION,
			transport: createObsidianGitHubTransport(PLUGIN_VERSION),
		});

		await expect(
			github.resolveIdentity({ username: 'octocat' }),
		).resolves.toMatchObject({
			kind: 'success',
			data: { username: 'octocat', githubAccountId: '42' },
		});
		expect(requestUrl).toHaveBeenCalledWith({
			url: 'https://api.github.com/users/octocat',
			method: 'GET',
			headers: VALID_HEADERS,
			throw: false,
		});
	});

	it.each([
		['other origin', 'https://example.com/users/octocat'],
		['plain HTTP', 'http://api.github.com/users/octocat'],
		['credentials', 'https://user:pass@api.github.com/users/octocat'],
		[
			'unsupported path',
			'https://api.github.com/repos/octocat/hello-world',
		],
		[
			'pull request query',
			'https://api.github.com/repos/octocat/hello-world/pulls/4?draft=true',
		],
		[
			'noncanonical pull request number',
			'https://api.github.com/repos/octocat/hello-world/pulls/04',
		],
		[
			'fragment',
			'https://api.github.com/users/octocat/events/public?per_page=100#page',
		],
		['empty identity fragment', 'https://api.github.com/users/octocat#'],
		['empty identity query', 'https://api.github.com/users/octocat?'],
		[
			'empty Events fragment',
			'https://api.github.com/users/octocat/events/public?per_page=100#',
		],
		[
			'malformed query',
			'https://api.github.com/users/octocat/events/public?page=1&per_page=99',
		],
		[
			'trailing query separator',
			'https://api.github.com/users/octocat/events/public?page=2&per_page=100&',
		],
		[
			'unsupported initial page',
			'https://api.github.com/users/octocat/events/public?page=1&per_page=100',
		],
		[
			'unsupported later page',
			'https://api.github.com/users/octocat/events/public?page=4&per_page=100',
		],
	] as const)('rejects %s before requestUrl', async (_case, url) => {
		const { createObsidianGitHubTransport } =
			await import('../src/adapters/github-transport');
		const transport = createObsidianGitHubTransport(PLUGIN_VERSION);

		await expect(
			transport({ url, headers: VALID_HEADERS }),
		).rejects.toThrow(GitHubTransportContractError);
		expect(requestUrl).not.toHaveBeenCalled();
	});

	it('rejects unapproved headers before requestUrl', async () => {
		const { createObsidianGitHubTransport } =
			await import('../src/adapters/github-transport');
		const transport = createObsidianGitHubTransport(PLUGIN_VERSION);

		await expect(
			transport({
				url: 'https://api.github.com/users/octocat',
				headers: { 'X-Probe-Token': 'secret' },
			}),
		).rejects.toThrow(GitHubTransportContractError);
		expect(requestUrl).not.toHaveBeenCalled();
	});

	it.each([
		['missing headers', {}],
		['wrong Accept', { ...VALID_HEADERS, Accept: 'text/plain' }],
		[
			'wrong User-Agent',
			{
				...VALID_HEADERS,
				'User-Agent':
					'DevRadar/0.1.0 (https://github.com/FerdiHS/devradar)',
			},
		],
		[
			'wrong API version',
			{ ...VALID_HEADERS, 'X-GitHub-Api-Version': '2022-11-28' },
		],
		[
			'duplicate API version casing',
			{ ...VALID_HEADERS, 'x-github-api-version': '2026-03-10' },
		],
		['Authorization', { ...VALID_HEADERS, Authorization: 'Bearer secret' }],
		['Cookie', { ...VALID_HEADERS, Cookie: 'secret=value' }],
	] as const)('rejects %s before requestUrl', async (_case, headers) => {
		const { createObsidianGitHubTransport } =
			await import('../src/adapters/github-transport');
		const transport = createObsidianGitHubTransport(PLUGIN_VERSION);

		await expect(
			transport({
				url: 'https://api.github.com/users/octocat',
				headers,
			}),
		).rejects.toThrow(GitHubTransportContractError);
		expect(requestUrl).not.toHaveBeenCalled();
	});

	it.each([
		'https://api.github.com/users/octocat/events/public?per_page=100',
		'https://api.github.com/users/octocat/events/public?page=2&per_page=100',
		'https://api.github.com/users/octocat/events/public?per_page=100&page=2',
		'https://api.github.com/users/octocat/events/public?page=3&per_page=100',
	])('accepts approved Events URL %s', async (url) => {
		requestUrl.mockResolvedValue({
			status: 200,
			headers: {},
			text: '{}',
		});
		const { createObsidianGitHubTransport } =
			await import('../src/adapters/github-transport');
		const transport = createObsidianGitHubTransport(PLUGIN_VERSION);

		await expect(
			transport({ url, headers: VALID_HEADERS }),
		).resolves.toMatchObject({
			status: 200,
			json: {},
		});
		expect(requestUrl).toHaveBeenCalledOnce();
	});

	it('accepts an exact Pull Request detail URL', async () => {
		requestUrl.mockResolvedValue({
			status: 200,
			headers: {},
			text: '{"title":"Improve docs"}',
		});
		const { createObsidianGitHubTransport } =
			await import('../src/adapters/github-transport');
		const transport = createObsidianGitHubTransport(PLUGIN_VERSION);

		await expect(
			transport({
				url: 'https://api.github.com/repos/octocat/hello-world/pulls/4',
				headers: VALID_HEADERS,
			}),
		).resolves.toMatchObject({
			status: 200,
			json: { title: 'Improve docs' },
		});
		expect(requestUrl).toHaveBeenCalledOnce();
	});

	it('fails closed on Mobile before requestUrl', async () => {
		obsidianPlatform.isMobileApp = true;
		const { createObsidianGitHubTransport } =
			await import('../src/adapters/github-transport');
		const transport = createObsidianGitHubTransport(PLUGIN_VERSION);

		await expect(
			transport({
				url: 'https://api.github.com/users/octocat',
				headers: VALID_HEADERS,
			}),
		).rejects.toThrow(GitHubTransportContractError);
		expect(requestUrl).not.toHaveBeenCalled();
	});

	it('allows Desktop transport when only the UI is in mobile mode', async () => {
		obsidianPlatform.isMobile = true;
		requestUrl.mockResolvedValue({
			status: 200,
			headers: {},
			text: '{}',
		});
		const { createObsidianGitHubTransport } =
			await import('../src/adapters/github-transport');
		const transport = createObsidianGitHubTransport(PLUGIN_VERSION);

		await expect(
			transport({
				url: 'https://api.github.com/users/octocat',
				headers: VALID_HEADERS,
			}),
		).resolves.toMatchObject({ status: 200, json: {} });
		expect(requestUrl).toHaveBeenCalledOnce();
	});

	it.each([302, 400, 500])(
		'preserves requestUrl status %i',
		async (status) => {
			requestUrl.mockResolvedValue({
				status,
				headers: {},
				text: '{}',
			});
			const { createObsidianGitHubTransport } =
				await import('../src/adapters/github-transport');
			const transport = createObsidianGitHubTransport(PLUGIN_VERSION);

			await expect(
				transport({
					url: 'https://api.github.com/users/octocat',
					headers: VALID_HEADERS,
				}),
			).resolves.toMatchObject({ status, json: {} });
		},
	);

	it('propagates requestUrl transport failures', async () => {
		const error = new Error('network unavailable');
		requestUrl.mockRejectedValue(error);
		const { createObsidianGitHubTransport } =
			await import('../src/adapters/github-transport');
		const transport = createObsidianGitHubTransport(PLUGIN_VERSION);

		await expect(
			transport({
				url: 'https://api.github.com/users/octocat',
				headers: VALID_HEADERS,
			}),
		).rejects.toBe(error);
	});

	it('passes the request contract to requestUrl', async () => {
		requestUrl.mockResolvedValue({
			status: 200,
			headers: { 'x-test': 'yes' },
			json: { ok: true },
			text: '{"ok":true}',
		});
		const { createObsidianGitHubTransport } =
			await import('../src/adapters/github-transport');
		const transport = createObsidianGitHubTransport(PLUGIN_VERSION);
		const result = await transport({
			url: 'https://api.github.com/users/octocat',
			headers: VALID_HEADERS,
		});

		expect(result).toEqual({
			status: 200,
			headers: { 'x-test': 'yes' },
			json: { ok: true },
		});
		expect(requestUrl).toHaveBeenCalledWith({
			url: 'https://api.github.com/users/octocat',
			method: 'GET',
			headers: VALID_HEADERS,
			throw: false,
		});
	});

	it('contains invalid JSON without reading requestUrl response.json', async () => {
		const response = {
			status: 200,
			headers: {},
			text: 'not-json',
		};
		Object.defineProperty(response, 'json', {
			get: () => {
				throw new Error('requestUrl JSON getter should not be used');
			},
		});
		requestUrl.mockResolvedValue(response);
		const { createObsidianGitHubTransport } =
			await import('../src/adapters/github-transport');
		const transport = createObsidianGitHubTransport(PLUGIN_VERSION);

		await expect(
			transport({
				url: 'https://api.github.com/users/octocat',
				headers: VALID_HEADERS,
			}),
		).resolves.toMatchObject({
			status: 200,
			json: undefined,
		});
	});
});
